#!/usr/bin/env bash
# Демо Дня 24: обязательные источники и цитаты + режим «не знаю» при слабом контексте.
set -euo pipefail
cd "$(dirname "$0")"

echo "########## 1. Обычный вопрос: ответ + источники + дословные цитаты (проверка кодом) ##########"
./run.sh ask "How accurately can humans detect that news articles were generated by GPT-3?"

echo
echo "########## 2. Вопрос мимо базы: агент обязан сказать «не знаю» и попросить уточнение ##########"
./run.sh ask "Какая столица Франции?"

echo
echo "########## 3. Полная проверка: 10 контрольных + 3 «мимо базы» ##########"
./run.sh verify

echo
echo "########## 4. Итоговый отчёт (output/verification.md) ##########"
cat output/verification.md
