/**
 * Контрольный вопрос из «усиления» задания: сам вопрос, ожидание (что должно быть
 * в ответе) и какие источники (разделы статьи) должны быть использованы.
 * Разделы сверяются с метаданным `section` извлечённых чанков.
 */
data class ControlQuestion(
    val question: String,
    val expectation: String,
    val expectedSections: List<String>,
)

/**
 * Мини-набор из 10 контрольных вопросов по базе (статья GPT-3, arXiv 2005.14165).
 * Смесь точечных фактов (цифры, которые модель без RAG обычно перевирает)
 * и «обзорных» вопросов по конкретным разделам.
 */
object ControlSet {
    val QUESTIONS = listOf(
        ControlQuestion(
            question = "How many parameters does the largest GPT-3 model have, and how many models in total were trained for the paper?",
            expectation = "175 billion parameters; 8 models were trained (from 125M to 175B).",
            expectedSections = listOf("1 Introduction", "2.1 Model and Architectures"),
        ),
        ControlQuestion(
            question = "Which datasets make up GPT-3's training mix and with what sampling weights?",
            expectation = "Common Crawl (filtered) 60%, WebText2 22%, Books1 8%, Books2 8%, Wikipedia 3%.",
            expectedSections = listOf("2.2 Training Dataset"),
        ),
        ControlQuestion(
            question = "What exactly do zero-shot, one-shot and few-shot mean in the paper, and how many examples K are typically used in few-shot?",
            expectation = "Settings without weight updates: 0 / 1 / K demonstrations in context; K is typically 10-100, bounded by the 2048-token context window.",
            expectedSections = listOf("2 Approach", "1 Introduction"),
        ),
        ControlQuestion(
            question = "What accuracy does GPT-3 achieve on LAMBADA in the few-shot setting and how does it compare to the previous state of the art?",
            expectation = "86.4% accuracy, an 18% absolute improvement over the previous SOTA.",
            expectedSections = listOf("3.1.2 LAMBADA"),
        ),
        ControlQuestion(
            question = "How accurately can humans detect that news articles were generated by the largest GPT-3 model?",
            expectation = "Mean human accuracy ~52%, barely above chance (50%).",
            expectedSections = listOf("3.9.4 News Article Generation", "E Human Quality Assessment of Synthetic News Articles"),
        ),
        ControlQuestion(
            question = "How did the authors measure test set contamination and what did they do about it?",
            expectation = "13-gram overlap search with training data, 'clean' vs 'dirty' benchmark versions, a bug in the initial filtering; most benchmarks showed little effect.",
            expectedSections = listOf("4 Measuring and Preventing Memorization Of Benchmarks", "C Details of Test Set Contamination Studies"),
        ),
        ControlQuestion(
            question = "What limitations of GPT-3 do the authors themselves acknowledge?",
            expectation = "Weaknesses in text synthesis and coherence over long passages, common-sense physics, no bidirectionality, sample inefficiency during pre-training, ambiguity of few-shot 'learning', expensive inference, limited interpretability.",
            expectedSections = listOf("5 Limitations"),
        ),
        ControlQuestion(
            question = "How much compute was used to train GPT-3 175B?",
            expectation = "Several thousand petaflop/s-days (~3640 petaflop/s-days, ~3.14e23 flops).",
            expectedSections = listOf("D Total Compute Used to Train Language Models", "5 Limitations"),
        ),
        ControlQuestion(
            question = "How well does GPT-3 perform on arithmetic tasks like 2-digit and 5-digit addition?",
            expectation = "Few-shot: ~100% on 2-digit addition, ~98-99% on 2-digit subtraction; accuracy drops sharply with more digits (~10% or less on 5-digit).",
            expectedSections = listOf("3.9.1 Arithmetic"),
        ),
        ControlQuestion(
            question = "What context window size does GPT-3 use and what attention pattern is used in its layers?",
            expectation = "Context window of 2048 tokens; alternating dense and locally banded sparse attention, as in the Sparse Transformer.",
            expectedSections = listOf("2.1 Model and Architectures"),
        ),
    )
}
